package com.tgcity.network.greendao;

import com.tgcity.network.greendao.model.HttpRequestLog;
import com.tgcity.network.greendao.model.SearchRecordModel;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * @author TGCity
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collegeDetailsCollegeContrastSchoolDtoDaoConfig;
    private final DaoConfig httpRequestLogDaoConfig;
    private final DaoConfig searchRecordModelDaoConfig;

    private final CollegeDetailsCollegeContrastSchoolDtoDao collegeDetailsCollegeContrastSchoolDtoDao;
    private final HttpRequestLogDao httpRequestLogDao;
    private final SearchRecordModelDao searchRecordModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collegeDetailsCollegeContrastSchoolDtoDaoConfig = daoConfigMap.get(CollegeDetailsCollegeContrastSchoolDtoDao.class).clone();
        collegeDetailsCollegeContrastSchoolDtoDaoConfig.initIdentityScope(type);


        httpRequestLogDaoConfig = daoConfigMap.get(HttpRequestLogDao.class).clone();
        httpRequestLogDaoConfig.initIdentityScope(type);

        searchRecordModelDaoConfig = daoConfigMap.get(SearchRecordModelDao.class).clone();
        searchRecordModelDaoConfig.initIdentityScope(type);

        collegeDetailsCollegeContrastSchoolDtoDao = new CollegeDetailsCollegeContrastSchoolDtoDao(collegeDetailsCollegeContrastSchoolDtoDaoConfig, this);
        httpRequestLogDao = new HttpRequestLogDao(httpRequestLogDaoConfig, this);
        searchRecordModelDao = new SearchRecordModelDao(searchRecordModelDaoConfig, this);

        registerDao(HttpRequestLog.class, httpRequestLogDao);
        registerDao(SearchRecordModel.class, searchRecordModelDao);
    }
    
    public void clear() {
        collegeDetailsCollegeContrastSchoolDtoDaoConfig.clearIdentityScope();
        httpRequestLogDaoConfig.clearIdentityScope();
        searchRecordModelDaoConfig.clearIdentityScope();
    }

    public CollegeDetailsCollegeContrastSchoolDtoDao getCollegeDetailsCollegeContrastSchoolDtoDao() {
        return collegeDetailsCollegeContrastSchoolDtoDao;
    }

    public HttpRequestLogDao getHttpRequestLogDao() {
        return httpRequestLogDao;
    }

    public SearchRecordModelDao getSearchRecordModelDao() {
        return searchRecordModelDao;
    }

}
